"""Baseline 5NF y FUD

Revision ID: 041c79c46d6f
Revises: 
Create Date: 2026-06-22 07:56:46.009179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041c79c46d6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat_cie_capitulo')
    op.drop_table('cat_cie_bloque')
    op.drop_table('cat_cie_categoria')
    op.create_index(op.f('ix_asentamiento_id_asen'), 'asentamiento', ['id_asen'], unique=False)
    op.alter_column('cat_cie_subcategoria', 'descripcion',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.create_index(op.f('ix_cat_cie_subcategoria_id_subcategoria'), 'cat_cie_subcategoria', ['id_subcategoria'], unique=False)
    op.drop_constraint('cat_cie_subcategoria_id_categoria_fkey', 'cat_cie_subcategoria', type_='foreignkey')
    op.create_index(op.f('ix_cat_discapacidad_id_dis'), 'cat_discapacidad', ['id_dis'], unique=False)
    op.create_index(op.f('ix_cat_estatus_juridico_id_est_jur'), 'cat_estatus_juridico', ['id_est_jur'], unique=False)
    op.create_index(op.f('ix_cat_grado_dependencia_id_gra_dep'), 'cat_grado_dependencia', ['id_gra_dep'], unique=False)
    op.create_index(op.f('ix_cat_lengua_id_len'), 'cat_lengua', ['id_len'], unique=False)
    op.create_index(op.f('ix_cat_lengua_inali_id_lengua'), 'cat_lengua_inali', ['id_lengua'], unique=False)
    op.create_index(op.f('ix_cat_medida_proteccion_id_med_pro'), 'cat_medida_proteccion', ['id_med_pro'], unique=False)
    op.create_index(op.f('ix_cat_modo_adquisicion_lengua_id_mod_adc'), 'cat_modo_adquisicion_lengua', ['id_mod_adc'], unique=False)
    op.create_index(op.f('ix_cat_nacionalidad_id_nac'), 'cat_nacionalidad', ['id_nac'], unique=False)
    op.create_index(op.f('ix_cat_nivel_competencia_oral_id_niv_com'), 'cat_nivel_competencia_oral', ['id_niv_com'], unique=False)
    op.create_index(op.f('ix_cat_roles_id_rol'), 'cat_roles', ['id_rol'], unique=False)
    op.create_index(op.f('ix_cat_sexo_id_sexo'), 'cat_sexo', ['id_sexo'], unique=False)
    op.create_index(op.f('ix_cat_tipo_contacto_id_tipo_con'), 'cat_tipo_contacto', ['id_tipo_con'], unique=False)
    op.create_index(op.f('ix_contacto_nna_id_contacto'), 'contacto_nna', ['id_contacto'], unique=False)
    op.create_index(op.f('ix_direccion_id_dir'), 'direccion', ['id_dir'], unique=False)
    op.create_index(op.f('ix_entidad_federativa_id_ent'), 'entidad_federativa', ['id_ent'], unique=False)
    op.create_index(op.f('ix_nna_id_nna'), 'nna', ['id_nna'], unique=False)
    op.drop_index('idx_nna_padecimiento_nna', table_name='nna_padecimiento')
    op.create_index(op.f('ix_nna_padecimiento_id_padecimiento'), 'nna_padecimiento', ['id_padecimiento'], unique=False)
    op.drop_constraint('nna_padecimiento_id_subcategoria_fkey', 'nna_padecimiento', type_='foreignkey')
    op.create_foreign_key(None, 'nna_padecimiento', 'cat_cie_subcategoria', ['id_subcategoria'], ['id_subcategoria'])
    op.drop_index('idx_nna_plantilla_nna', table_name='nna_plantilla')
    op.drop_index('idx_nna_plantilla_plantilla', table_name='nna_plantilla')
    op.drop_index('uq_nna_plantilla_activa', table_name='nna_plantilla', postgresql_where='activa')
    op.create_index(op.f('ix_nna_plantilla_id_nna_plantilla'), 'nna_plantilla', ['id_nna_plantilla'], unique=False)
    op.drop_constraint('nna_plantilla_id_plantilla_fkey', 'nna_plantilla', type_='foreignkey')
    op.create_foreign_key(None, 'nna_plantilla', 'plantilla', ['id_plantilla'], ['id_plantilla'])
    op.drop_index('idx_nna_situacion_legal_nna', table_name='nna_situacion_legal')
    op.create_index(op.f('ix_nna_situacion_legal_id_sit_legal'), 'nna_situacion_legal', ['id_sit_legal'], unique=False)
    op.drop_constraint('nna_situacion_legal_id_est_jur_fkey', 'nna_situacion_legal', type_='foreignkey')
    op.drop_constraint('nna_situacion_legal_id_med_pro_fkey', 'nna_situacion_legal', type_='foreignkey')
    op.create_foreign_key(None, 'nna_situacion_legal', 'cat_medida_proteccion', ['id_med_pro'], ['id_med_pro'])
    op.create_foreign_key(None, 'nna_situacion_legal', 'cat_estatus_juridico', ['id_est_jur'], ['id_est_jur'])
    op.alter_column('personal', 'contrasena',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_personal_id_personal'), 'personal', ['id_personal'], unique=False)
    op.drop_constraint('fk_personal_rol', 'personal', type_='foreignkey')
    op.create_foreign_key(None, 'personal', 'cat_roles', ['id_rol'], ['id_rol'])
    op.drop_index('idx_personal_lengua_id_len', table_name='personal_lengua')
    op.drop_index('idx_personal_lengua_id_personal', table_name='personal_lengua')
    op.drop_constraint('personal_lengua_id_mod_adc_fkey', 'personal_lengua', type_='foreignkey')
    op.drop_constraint('personal_lengua_id_len_fkey', 'personal_lengua', type_='foreignkey')
    op.drop_constraint('personal_lengua_id_niv_com_fkey', 'personal_lengua', type_='foreignkey')
    op.create_foreign_key(None, 'personal_lengua', 'cat_modo_adquisicion_lengua', ['id_mod_adc'], ['id_mod_adc'])
    op.create_foreign_key(None, 'personal_lengua', 'cat_lengua', ['id_len'], ['id_len'])
    op.create_foreign_key(None, 'personal_lengua', 'cat_nivel_competencia_oral', ['id_niv_com'], ['id_niv_com'])
    op.create_index(op.f('ix_plantilla_id_plantilla'), 'plantilla', ['id_plantilla'], unique=False)
    op.drop_index('idx_plantilla_personal_personal', table_name='plantilla_personal')
    op.create_index(op.f('ix_tutor_id_tutor'), 'tutor', ['id_tutor'], unique=False)
    op.drop_index('idx_tutor_discapacidad_id_dis', table_name='tutor_discapacidad')
    op.drop_index('idx_tutor_discapacidad_id_tutor', table_name='tutor_discapacidad')
    op.drop_constraint('tutor_discapacidad_id_gra_dep_fkey', 'tutor_discapacidad', type_='foreignkey')
    op.drop_constraint('tutor_discapacidad_id_dis_fkey', 'tutor_discapacidad', type_='foreignkey')
    op.create_foreign_key(None, 'tutor_discapacidad', 'cat_discapacidad', ['id_dis'], ['id_dis'])
    op.create_foreign_key(None, 'tutor_discapacidad', 'cat_grado_dependencia', ['id_gra_dep'], ['id_gra_dep'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutor_discapacidad', type_='foreignkey')
    op.drop_constraint(None, 'tutor_discapacidad', type_='foreignkey')
    op.create_foreign_key('tutor_discapacidad_id_dis_fkey', 'tutor_discapacidad', 'cat_discapacidad', ['id_dis'], ['id_dis'], ondelete='CASCADE')
    op.create_foreign_key('tutor_discapacidad_id_gra_dep_fkey', 'tutor_discapacidad', 'cat_grado_dependencia', ['id_gra_dep'], ['id_gra_dep'], ondelete='SET NULL')
    op.create_index('idx_tutor_discapacidad_id_tutor', 'tutor_discapacidad', ['id_tutor'], unique=False)
    op.create_index('idx_tutor_discapacidad_id_dis', 'tutor_discapacidad', ['id_dis'], unique=False)
    op.drop_index(op.f('ix_tutor_id_tutor'), table_name='tutor')
    op.create_index('idx_plantilla_personal_personal', 'plantilla_personal', ['id_personal'], unique=False)
    op.drop_index(op.f('ix_plantilla_id_plantilla'), table_name='plantilla')
    op.drop_constraint(None, 'personal_lengua', type_='foreignkey')
    op.drop_constraint(None, 'personal_lengua', type_='foreignkey')
    op.drop_constraint(None, 'personal_lengua', type_='foreignkey')
    op.create_foreign_key('personal_lengua_id_niv_com_fkey', 'personal_lengua', 'cat_nivel_competencia_oral', ['id_niv_com'], ['id_niv_com'], ondelete='SET NULL')
    op.create_foreign_key('personal_lengua_id_len_fkey', 'personal_lengua', 'cat_lengua', ['id_len'], ['id_len'], ondelete='CASCADE')
    op.create_foreign_key('personal_lengua_id_mod_adc_fkey', 'personal_lengua', 'cat_modo_adquisicion_lengua', ['id_mod_adc'], ['id_mod_adc'], ondelete='SET NULL')
    op.create_index('idx_personal_lengua_id_personal', 'personal_lengua', ['id_personal'], unique=False)
    op.create_index('idx_personal_lengua_id_len', 'personal_lengua', ['id_len'], unique=False)
    op.drop_constraint(None, 'personal', type_='foreignkey')
    op.create_foreign_key('fk_personal_rol', 'personal', 'cat_roles', ['id_rol'], ['id_rol'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_personal_id_personal'), table_name='personal')
    op.alter_column('personal', 'contrasena',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'nna_situacion_legal', type_='foreignkey')
    op.drop_constraint(None, 'nna_situacion_legal', type_='foreignkey')
    op.create_foreign_key('nna_situacion_legal_id_med_pro_fkey', 'nna_situacion_legal', 'cat_medida_proteccion', ['id_med_pro'], ['id_med_pro'], ondelete='RESTRICT')
    op.create_foreign_key('nna_situacion_legal_id_est_jur_fkey', 'nna_situacion_legal', 'cat_estatus_juridico', ['id_est_jur'], ['id_est_jur'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_nna_situacion_legal_id_sit_legal'), table_name='nna_situacion_legal')
    op.create_index('idx_nna_situacion_legal_nna', 'nna_situacion_legal', ['id_nna'], unique=False)
    op.drop_constraint(None, 'nna_plantilla', type_='foreignkey')
    op.create_foreign_key('nna_plantilla_id_plantilla_fkey', 'nna_plantilla', 'plantilla', ['id_plantilla'], ['id_plantilla'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_nna_plantilla_id_nna_plantilla'), table_name='nna_plantilla')
    op.create_index('uq_nna_plantilla_activa', 'nna_plantilla', ['id_nna'], unique=False, postgresql_where='activa')
    op.create_index('idx_nna_plantilla_plantilla', 'nna_plantilla', ['id_plantilla'], unique=False)
    op.create_index('idx_nna_plantilla_nna', 'nna_plantilla', ['id_nna'], unique=False)
    op.drop_constraint(None, 'nna_padecimiento', type_='foreignkey')
    op.create_foreign_key('nna_padecimiento_id_subcategoria_fkey', 'nna_padecimiento', 'cat_cie_subcategoria', ['id_subcategoria'], ['id_subcategoria'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_nna_padecimiento_id_padecimiento'), table_name='nna_padecimiento')
    op.create_index('idx_nna_padecimiento_nna', 'nna_padecimiento', ['id_nna'], unique=False)
    op.drop_index(op.f('ix_nna_id_nna'), table_name='nna')
    op.drop_index(op.f('ix_entidad_federativa_id_ent'), table_name='entidad_federativa')
    op.drop_index(op.f('ix_direccion_id_dir'), table_name='direccion')
    op.drop_index(op.f('ix_contacto_nna_id_contacto'), table_name='contacto_nna')
    op.drop_index(op.f('ix_cat_tipo_contacto_id_tipo_con'), table_name='cat_tipo_contacto')
    op.drop_index(op.f('ix_cat_sexo_id_sexo'), table_name='cat_sexo')
    op.drop_index(op.f('ix_cat_roles_id_rol'), table_name='cat_roles')
    op.drop_index(op.f('ix_cat_nivel_competencia_oral_id_niv_com'), table_name='cat_nivel_competencia_oral')
    op.drop_index(op.f('ix_cat_nacionalidad_id_nac'), table_name='cat_nacionalidad')
    op.drop_index(op.f('ix_cat_modo_adquisicion_lengua_id_mod_adc'), table_name='cat_modo_adquisicion_lengua')
    op.drop_index(op.f('ix_cat_medida_proteccion_id_med_pro'), table_name='cat_medida_proteccion')
    op.drop_index(op.f('ix_cat_lengua_inali_id_lengua'), table_name='cat_lengua_inali')
    op.drop_index(op.f('ix_cat_lengua_id_len'), table_name='cat_lengua')
    op.drop_index(op.f('ix_cat_grado_dependencia_id_gra_dep'), table_name='cat_grado_dependencia')
    op.drop_index(op.f('ix_cat_estatus_juridico_id_est_jur'), table_name='cat_estatus_juridico')
    op.drop_index(op.f('ix_cat_discapacidad_id_dis'), table_name='cat_discapacidad')
    op.create_foreign_key('cat_cie_subcategoria_id_categoria_fkey', 'cat_cie_subcategoria', 'cat_cie_categoria', ['id_categoria'], ['id_categoria'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_cat_cie_subcategoria_id_subcategoria'), table_name='cat_cie_subcategoria')
    op.alter_column('cat_cie_subcategoria', 'descripcion',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_index(op.f('ix_asentamiento_id_asen'), table_name='asentamiento')
    op.create_table('cat_cie_categoria',
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_bloque', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.CHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_bloque'], ['cat_cie_bloque.id_bloque'], name='cat_cie_categoria_id_bloque_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_categoria', name='cat_cie_categoria_pkey'),
    sa.UniqueConstraint('codigo', name='cat_cie_categoria_codigo_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cat_cie_bloque',
    sa.Column('id_bloque', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_capitulo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_inicio', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('codigo_fin', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_capitulo'], ['cat_cie_capitulo.id_capitulo'], name='cat_cie_bloque_id_capitulo_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_bloque', name='cat_cie_bloque_pkey')
    )
    op.create_table('cat_cie_capitulo',
    sa.Column('id_capitulo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo_romano', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_capitulo', name='cat_cie_capitulo_pkey'),
    sa.UniqueConstraint('codigo_romano', name='cat_cie_capitulo_codigo_romano_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
